//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string contrasenia { get; set; }
        public string correo { get; set; }
        public int rol_fk { get; set; }
        public int imagen_fk { get; set; }
    
        public virtual ImagenesEmpleado ImagenesEmpleado { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
