//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orden()
        {
            this.Envio = new HashSet<Envio>();
            this.Orden_Producto = new HashSet<Orden_Producto>();
        }
    
        public int id { get; set; }
        public int id_cliente_fk { get; set; }
        public int id_direccion_fk { get; set; }
        public int id_tarjeta_fk { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string numero_confirmacion { get; set; }
        public decimal total { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Direccion Direccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Envio> Envio { get; set; }
        public virtual Tarjeta Tarjeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orden_Producto> Orden_Producto { get; set; }
    }
}
